import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import readline from 'node:readline/promises';
import YAML from 'yaml';
import { PKG_ROOT } from '../compose/composer.js';
import { parseConfig } from '../config.js';
import { runBuild } from './build.js';

const DEST = () => path.resolve('ticket-flow.config.yaml');
const ALREADY = 'ticket-flow.config.yaml already exists. Edit it, or re-run with --force to overwrite.';

function git(cmd, cwd) {
  return execSync(`git ${cmd}`, { cwd, stdio: ['ignore', 'pipe', 'ignore'], encoding: 'utf8' }).trim();
}

// Best-effort test-command detection from stack marker files — first match wins, null when
// nothing recognizable is found. Never throws.
export function detectTestCommand(cwd) {
  const read = (f) => fs.readFileSync(path.join(cwd, f), 'utf8');
  const has = (f) => fs.existsSync(path.join(cwd, f));
  const grep = (f, re) => {
    try {
      return re.test(read(f));
    } catch {
      return false; // file absent or unreadable
    }
  };

  try {
    const pkg = JSON.parse(read('package.json'));
    if (pkg.scripts?.test && !/no test specified/.test(pkg.scripts.test)) return 'npm test';
  } catch {
    /* no (or unparseable) package.json — keep probing */
  }
  if (grep('Makefile', /^test:/m)) return 'make test';
  if (has('pom.xml')) return 'mvn test';
  if (has('build.gradle') || has('build.gradle.kts')) return has('gradlew') ? './gradlew test' : 'gradle test';
  if (grep('pyproject.toml', /\[tool\.pytest/) || grep('pytest.ini', /^\[pytest\]/m) || grep('setup.cfg', /^\[tool:pytest\]/m)) {
    return 'pytest';
  }
  if (has('go.mod')) return 'go test ./...';
  if (has('Cargo.toml')) return 'cargo test';
  return null;
}

// Best-effort defaults from the surrounding repo — never throws.
export function detectDefaults(cwd) {
  const detected = detectTestCommand(cwd);
  const d = {
    projectName: path.basename(cwd),
    baseBranch: 'main',
    testCommand: detected ?? 'npm test',
    testCommandDetected: detected !== null,
  };

  try {
    const url = git('remote get-url origin', cwd);
    const m = url.match(/[/:]([^/]+)\/([^/]+?)(?:\.git)?$/);
    if (m) d.projectName = m[2];
  } catch {
    /* no remote */
  }

  try {
    d.baseBranch = git('symbolic-ref --short refs/remotes/origin/HEAD', cwd).replace(/^origin\//, '');
  } catch {
    try {
      const b = git('branch --show-current', cwd);
      if (b) d.baseBranch = b;
    } catch {
      /* not a git repo */
    }
  }

  return d;
}

// Pure: shape wizard answers into a minimal, schema-valid config object.
export function assembleConfig(a) {
  return {
    // ticketPrefix and backend.project are intentionally omitted — the generated skills
    // resolve the active project and read the ticket prefix from ids at runtime. Both remain
    // optional config knobs for anyone who wants to pin them.
    project: { name: a.projectName },
    backend: { type: a.backendType },
    git: { baseBranch: a.baseBranch },
    test: { command: a.testCommand },
    tools: a.tools,
  };
}

const HEADER = `# ticket-flow.config.yaml — generated by \`ticket-flow init\`.
# Advanced knobs (state names, branchPattern, mergeStrategy, conventions, review checks)
# fall back to sensible defaults; see templates/ticket-flow.config.yaml to customize them.

`;

export function configToYaml(config) {
  return HEADER + YAML.stringify(config);
}

function answersFromDetected(d) {
  return {
    projectName: d.projectName,
    backendType: 'linear',
    baseBranch: d.baseBranch,
    testCommand: d.testCommand,
    tools: ['claude'],
  };
}

async function promptAnswers(d) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const ask = async (q, def) => (await rl.question(`${q}${def ? ` (${def})` : ''}: `)).trim() || def;
  try {
    const projectName = await ask('Project name', d.projectName);
    const backendType = await ask('Backend [linear/jira]', 'linear');
    const baseBranch = await ask('Base branch', d.baseBranch);
    const testCommand = await ask('Test command', d.testCommand);
    const toolsRaw = await ask('Tools (comma-separated: claude,copilot,opencode)', 'claude');
    return {
      projectName,
      backendType,
      baseBranch,
      testCommand,
      tools: toolsRaw.split(',').map((s) => s.trim()).filter(Boolean),
    };
  } finally {
    rl.close();
  }
}

// Interactive wizard (TTY): detect -> prompt -> validate -> write -> offer build.
export async function initInteractive(flags = {}) {
  const dest = DEST();
  if (fs.existsSync(dest) && !flags.force) {
    console.log(ALREADY);
    return dest;
  }

  console.log('Setting up ticket-flow — press enter to accept each default.\n');
  const answers = await promptAnswers(detectDefaults(process.cwd()));
  const yaml = configToYaml(assembleConfig(answers));
  parseConfig(yaml); // throws with a readable message if the answers are invalid

  fs.writeFileSync(dest, yaml);
  console.log(`\nCreated ${path.relative(process.cwd(), dest)}`);

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const build = (await rl.question('Build the skills now? [Y/n]: ')).trim().toLowerCase();
  rl.close();
  if (build === '' || build === 'y' || build === 'yes') runBuild({});
  else console.log('Run `ticket-flow build` when you are ready.');
  return dest;
}

// Non-interactive: write a config straight from detected defaults.
export function initDefaults(flags = {}) {
  const dest = DEST();
  if (fs.existsSync(dest) && !flags.force) {
    console.log(ALREADY);
    return dest;
  }
  const detected = detectDefaults(process.cwd());
  fs.writeFileSync(dest, configToYaml(assembleConfig(answersFromDetected(detected))));
  console.log(`Created ${path.relative(process.cwd(), dest)} (from detected defaults)`);
  if (!detected.testCommandDetected) {
    console.log('⚠ could not detect a test command — edit test.command in ticket-flow.config.yaml');
  }
  return dest;
}

// Original behavior: copy the annotated template verbatim.
export function init({ force = false } = {}) {
  const src = path.join(PKG_ROOT, 'templates', 'ticket-flow.config.yaml');
  const dest = DEST();

  if (fs.existsSync(dest) && !force) {
    console.log(`ticket-flow.config.yaml already exists. Edit it, or re-run with --force to overwrite.`);
    return dest;
  }
  fs.copyFileSync(src, dest);
  console.log(`Created ${path.relative(process.cwd(), dest)}`);
  console.log(`\nNext:`);
  console.log(`  1. Edit ticket-flow.config.yaml for your project (name, backend, baseBranch, testCommand).`);
  console.log(`  2. Run \`ticket-flow build\` to generate the skills for your tools.`);
  return dest;
}

// Entry point the CLI uses: interactive when a TTY, --defaults for detected config, else template.
export async function runInit(flags = {}) {
  if (flags.defaults) return initDefaults(flags);
  if (process.stdin.isTTY) return initInteractive(flags);
  return init(flags);
}
